<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>nut</string>
    </array>
    <key>name</key>
    <string>Squirrel</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>\b(if|else|while|do|for|foreach|break|continue|switch|case|default)\b</string>
            <key>name</key>
            <string>keyword.control.flow.squirrel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(return|throw|resume|yield)\b</string>
            <key>name</key>
            <string>keyword.control.flow.jump.squirrel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(try|catch)\b</string>
            <key>name</key>
            <string>keyword.control.exception.squirrel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(clone|delete|in|typeof|instanceof)\b</string>
            <key>name</key>
            <string>keyword.operator.squirrel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(true|false|null)\b</string>
            <key>name</key>
            <string>constant.language.squirrel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(this|vargc|vargv|parent)\b</string>
            <key>name</key>
            <string>variable.language.squirrel</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.squirrel</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.squirrel</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.squirrel</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>@"</string>
            <key>end</key>
            <string>"(?!")</string>
            <key>name</key>
            <string>string.quoted.other.squirrel</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>""</string>
                    <key>name</key>
                    <string>constant.character.squirrel</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>name</key>
            <string>string.quoted.double.squirrel</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\([tabnrvf\\"'0]|x[\da-fA-F]{1,4})</string>
                    <key>name</key>
                    <string>constant.character.escape.squirrel</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\\x?.</string>
                    <key>name</key>
                    <string>invalid.character.escape</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\n</string>
                    <key>name</key>
                    <string>invalid.string.newline</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>'([^\\']|\\([tabnrvf\\"'0]|x[\da-fA-F]{1,4}))'</string>
            <key>name</key>
            <string>constant.character.squirrel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>'(''|[^']*'?)</string>
            <key>name</key>
            <string>invalid.character</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(0|[1-9]\d*|0[xX][\da-fA-F]{1,8}|0[0-3]?[0-7]{1,10})\b</string>
            <key>name</key>
            <string>constant.numeric.squirrel</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.declaration.squirrel</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>variable.other.local.squirrel</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(local)\b(?:\s+([a-zA-Z_][a-zA-Z\d_]*))?</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.declaration.squirrel</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>name.function.squirrel</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(function)\b(?:\s+([a-zA-Z_][a-zA-Z\d_]*))?</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.declaration.squirrel</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>name.type.squirrel</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(class)\b(?:\s+([a-zA-Z_][a-zA-Z\d_]*))?</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.nut</string>
    <key>uuid</key>
    <string>907f94ac-e9a7-41ea-b9c0-f0f9bb3e8ed6</string>
</dict>
</plist>
